config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  	resources :clientes do
  		resources :pacotes
  	end
  	resources :articles

	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pacotes, dependent: :destroy
  validates :Nome, presence: true
  validates :CPF, presence: true
  validates :Email, presence: true
  validates :Endereco, presence: true
  validates :Data_de_Nascimento, presence: true
end

app/models/pacote.rb
class Pacote < ApplicationRecord
  belongs_to :cliente
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
  end
  def create
  @article = Article.new(params.require(:article).permit(:title, :text))
  @article.save
  redirect_to @article
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  def index
    @clientes = Cliente.all
  end

  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
    redirect_to @cliente
    else
      render 'new'
    end
  end

  def update
    @cliente = Cliente.find(params[:id])

    if @cliente.update(cliente_params)
      redirect_to @cliente
    else
      render 'edit'
    end
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    redirect_to clientes_path
  end

  private
  def cliente_params
    params.require(:cliente).permit(:Nome, :CPF, :Email, :Endereco, :Data_de_Nascimento)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Hello World<h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/clientes/index.html.erb
<h1>Clientes</h1>
<%= link_to 'Cadastre-se', new_cliente_path %>
<table>
	<tr>
		<th>Nome</th>
		<th>CPF</th>
		<th>Email</th>
		<th>Endereco</th>
		<th>Data_de_Nascimento</th>
		<th colspan="3"></th>
	</tr>
	<% @clientes.each do |cliente|%>
		<tr>
		<td><%= cliente.Nome %></td>
		<td><%= cliente.CPF %></td>
		<td><%= cliente.Email %></td>
		<td><%= cliente.Endereco %></td>
		<td><%= cliente.Data_de_Nascimento %></td>
		<td><%= link_to 'Show', cliente_path(cliente) %></td>	
	    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
	    <td><%= link_to 'Destroy', cliente_path(cliente),
              method: :delete,
              data: { confirm: 'Tem certeza?' } %></td>
		</tr>
	<%end%>
</table>
	<%= link_to 'Voltar à pagina anterior', controller: 'welcome' %>

app/views/clientes/new.html.erb
<h1>Página de cadastro</h1><br>

<%= render 'form' %>
 
<%= link_to 'Voltar à pagina anterior', clientes_path %>

app/views/clientes/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @cliente.Nome %>
</p>
 
<p>
  <strong>CPF:</strong>
  <%= @cliente.CPF %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @cliente.Email %>
</p>
 
<p>
  <strong>Endereço:</strong>
  <%= @cliente.Endereco %>
</p>
 
<p>
  <strong>Data_de_Nascimento:</strong>
  <%= @cliente.Data_de_Nascimento %>
</p>

<h2>Pagamentos</h2>
<%= render @cliente.pacotes %>
 
<h2>Seja sócio:</h2>
<%= render 'pacotes/form' %>

<%= link_to 'Edit' , edit_cliente_path(@cliente)%>
<%= link_to 'Voltar à pagina anterior', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Link</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Cadastro', controller: 'clientes' %>